<?php

return array(
    array(
        'title' => 'Top Sponsor',
        'description' => 'Displays the list of top sponsors.',
        'category' => 'Custom',
        'type' => 'widget',
        'name' => 'custom.sponsor-popular',
        'isPaginated' => true,
        'defaultParams' => array('title' => 'Top Sponsor', ),
        'requirements' => array('no-subject', ),
        ),
    array(
        'title' => 'Newest Sponsor',
        'description' => 'Displays the list of most newest sponsors.',
        'category' => 'Custom',
        'type' => 'widget',
        'name' => 'custom.sponsor-newest',
        'isPaginated' => true,
        'defaultParams' => array('title' => 'Newest Sponsor', ),
        'requirements' => array('no-subject', ),
        ),
    array(
        'title' => 'List Student',
        'description' => 'Displays the list of student.',
        'category' => 'Custom',
        'type' => 'widget',
        'name' => 'custom.list-students',
        'isPaginated' => true,
        'requirements' => array('no-subject', ),
        ),
    array(
        'title' => 'My widget',
        'description' => 'Displays the list of student.',
        'category' => 'Custom',
        'type' => 'widget',
        'name' => 'custom.mywidget',
        'isPaginated' => true,
        'requirements' => array('no-subject', ),
        ),
    array(
        'title' => 'Search Student',
        'description' => 'Displays the list of student.',
        'category' => 'Custom',
        'type' => 'widget',
        'name' => 'custom.search-student',
        'isPaginated' => true,
        'defaultParams' => array('title' => 'Lọc sinh viên', ),
        'requirements' => array('no-subject', ),
        ),
    array(
        'title' => 'Connect',
        'description' => 'Displays the list of student activity',
        'category' => 'Custom',
        'type' => 'widget',
        'name' => 'custom.connect',
        'isPaginated' => true,
        'requirements' => array('no-subject', ),
        ),
    array(
        'title' => 'Connect Update Notification',
        'description' => 'Displays the list of student activity',
        'category' => 'Custom',
        'type' => 'widget',
        'name' => 'custom.connect-update',
        'isPaginated' => true,
        'requirements' => array('no-subject', ),
        ),
    array(
        'title' => 'List Student Enough',
        'description' => 'Displays the list of student enough money.',
        'category' => 'Custom',
        'type' => 'widget',
        'name' => 'custom.list-student-enough',
        'isPaginated' => true,
        'defaultParams' => array('title' => 'Students enough money', ),
        'requirements' => array('no-subject', ),
        ),
    )

?>